/** Documentation Comment */
package Comments {
	doc /* Documentation about Package */
	comment /** Comment about Comment */
	comment cmt /* Named Comment */	
	comment cmt_cmtc about cmt /* Other Comment about Comment */
	
	comment /** Documention Comment on Block */
	part def C {
		doc /* Documentation in Part Def */
		comment /* Comment in Part Def */
		comment about Comments /* Comment about Package */
	}
}